# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "A helpful CircleCI and GitHub tool."
  homepage "https://github.com/hubci/arc"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hubci/arc/releases/download/v0.4.1/arc-v0.4.1-macos-arm64.tar.gz"
      sha256 "4ade044f1aed21985b7bdcfd320030d5e161fc339b3ad014806f4f4f23ec27de"

      def install
        bin.install "arc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubci/arc/releases/download/v0.4.1/arc-v0.4.1-macos-amd64.tar.gz"
      sha256 "6e4d76255e805f8b37b96489498c31a8329674d74e08c37319d3e73456eb1558"

      def install
        bin.install "arc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hubci/arc/releases/download/v0.4.1/arc-v0.4.1-linux-arm64.tar.gz"
      sha256 "96413fbd2c7e1ba363da32329ce6d60bcdf0bb3653705c7fdd73f09d218957cd"

      def install
        bin.install "arc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubci/arc/releases/download/v0.4.1/arc-v0.4.1-linux-amd64.tar.gz"
      sha256 "3bc4f5df6f7dc971c07e118502dc42e24b1e393e6a397dac8b0c1ee8801f5885"

      def install
        bin.install "arc"
      end
    end
  end

  test do
    system "#{bin}/arc", "help"
  end
end
