# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "A helpful CircleCI and GitHub tool."
  homepage "https://github.com/hubci/arc"
  version "0.2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/hubci/arc/releases/download/v0.2.0/arc-v0.2.0-macos-amd64.tar.gz"
    sha256 "7710897c9b814e480e5d1a6f784a9d6db2f3eb41249799c368872fe7e1215e24"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/hubci/arc/releases/download/v0.2.0/arc-v0.2.0-macos-arm64.tar.gz"
    sha256 "a9657f73642f0f418b1a69a7f027444e011a1ed420a0c66e14c24c795a3698e3"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/hubci/arc/releases/download/v0.2.0/arc-v0.2.0-linux-amd64.tar.gz"
    sha256 "ec1a93485dbda9fe3e30cc7ebda0010f4cb8568a0b3fb7c742927316b1847946"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/hubci/arc/releases/download/v0.2.0/arc-v0.2.0-linux-arm64.tar.gz"
    sha256 "2ef5925489567e7303c14fbe7aeab6eebfbcdb70b2788b3f05a5174448f68031"
  end

  def install
    bin.install "arc"
  end

  test do
    system "#{bin}/arc", "help"
  end
end
