# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "A helpful CircleCI and GitHub tool."
  homepage "https://github.com/hubci/arc"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hubci/arc/releases/download/v0.3.0/arc-v0.3.0-macos-arm64.tar.gz"
      sha256 "5a2a5615a732cc80c283f34e38c1aea19f9c192bf9fa47370a8ac63861088692"

      def install
        bin.install "arc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubci/arc/releases/download/v0.3.0/arc-v0.3.0-macos-amd64.tar.gz"
      sha256 "144cc920a96294e5306cc1217499cc9b0cb7df62a4073d2f6b290d95fb080f45"

      def install
        bin.install "arc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hubci/arc/releases/download/v0.3.0/arc-v0.3.0-linux-arm64.tar.gz"
      sha256 "d2147c689ae9b2048345c93380d203cd458c1e27def4438e4fdf25eff2fca1a2"

      def install
        bin.install "arc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hubci/arc/releases/download/v0.3.0/arc-v0.3.0-linux-amd64.tar.gz"
      sha256 "29a7fdf73c5f15ab81ed957040897190fd44eadcc0266ec846873803fa851b76"

      def install
        bin.install "arc"
      end
    end
  end

  test do
    system "#{bin}/arc", "help"
  end
end
